# Generated by Django 5.2.1 on 2025-05-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="img_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
