# Generated by Django 5.2.1 on 2025-05-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_post_is_published_alter_post_img_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="external_img_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="img_url",
            field=models.ImageField(blank=True, null=True, upload_to="post/images"),
        ),
    ]
